name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull TinyGo
      run: docker pull tinygo/tinygo:0.26.0

    - name: Build Project
      run: docker run -v $(pwd):$(pwd) -w $(pwd)/internal/restic tinygo/tinygo tinygo build -o restic.wasm -target wasi

